# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFQL4AijihV4JzmT56mX-nIE0kpJMV10
"""

"""
Credit Lab
"""

import streamlit as st
import pandas as pd
import sys

# Configuration de la page
st.set_page_config(
    page_title="Système de Crédit Bancaire",
    page_icon="💰",
    layout="wide"
)

# Ajouter le chemin pour importer les modules
sys.path.append('./src/')
sys.path.append('./src/preprocessing/')

# Imports
try:
    from credit_engine import CreditDecisionSystem
except ImportError:
    st.error("Erreur : Impossible d'importer credit_engine. Vérifiez le chemin.")
    st.stop()

# ==============================================================================
# INITIALISATION DU SYSTÈME
# ==============================================================================

@st.cache_resource
def load_system():
    """Charge le système une seule fois (mise en cache)."""
    try:
        system = CreditDecisionSystem('./outputs/models/')
        return system
    except Exception as e:
        st.error(f"Erreur lors du chargement du système : {e}")
        return None

# ==============================================================================
# INTERFACE PRINCIPALE
# ==============================================================================

def main():
    # Titre
    st.title("Système de Décision de Crédit Bancaire")
    st.markdown("---")

    # Charger le système
    with st.spinner("Chargement du système..."):
        system = load_system()

    if system is None:
        st.error("Le système n'a pas pu être chargé. Vérifiez que les modèles sont bien dans ./models/")
        st.stop()

    st.success("Système chargé avec succès")

    # Sidebar - Navigation
    st.sidebar.title("Navigation")
    page = st.sidebar.radio(
        "Choisissez une page :",
        ["Simulateur Client", "Batch Upload", "À propos"]
    )

    if page == "Simulateur Client":
        page_simulateur(system)
    elif page == "Batch Upload":
        page_batch(system)
    elif page == "À propos":
        page_about()

# ==============================================================================
# PAGE 1 : SIMULATEUR CLIENT
# ==============================================================================

def page_simulateur(system):
    st.header(" Simulateur de Demande de Crédit")
    st.markdown("Renseignez les informations du client pour obtenir une décision automatique.")

    # Formulaire en colonnes
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Informations Personnelles")
        age = st.number_input("Âge", min_value=18, max_value=80, value=35, step=1)
        niveau_etude = st.selectbox(
            "Niveau d'études",
            ["Bac", "Licence", "Master", "Doctorat"]
        )
        ville = st.selectbox(
            "Ville de résidence",
            ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Autre"]
        )

    with col2:
        st.subheader("Informations Financières")
        salaire = st.number_input(
            "Salaire annuel (€)",
            min_value=0,
            max_value=200000,
            value=45000,
            step=1000
        )
        epargne = st.number_input(
            "Épargne totale (€)",
            min_value=0,
            max_value=500000,
            value=10000,
            step=1000
        )
        score_credit = st.slider(
            "Score de crédit externe",
            min_value=0,
            max_value=100,
            value=75,
            step=5
        )

    # Paramètres du prêt
    st.subheader("Paramètres du Prêt")
    duration = st.slider(
        "Durée du prêt (mois)",
        min_value=12,
        max_value=120,
        value=60,
        step=12
    )

    # Bouton de simulation
    if st.button("Simuler la Demande", type="primary"):
        # Créer le DataFrame client
        client = pd.DataFrame({
            'Age': [age],
            'Salaire_Annuel': [salaire],
            'Epargne_Totale': [epargne],
            'Score_Credit_Externe': [score_credit],
            'Niveau_Etude': [niveau_etude],
            'Ville': [ville]
        })

        # Prédiction
        with st.spinner("Analyse en cours..."):
            try:
                decision = system.predict(client, duration_months=duration)

                # Affichage de la décision
                st.markdown("---")
                display_decision(decision)

            except Exception as e:
                st.error(f"Erreur lors de la prédiction : {e}")
                st.exception(e)

# ==============================================================================
# PAGE 2 : BATCH UPLOAD
# ==============================================================================

def page_batch(system):
    st.header("📊 Analyse en Batch")
    st.markdown("Uploadez un fichier CSV contenant plusieurs clients.")

    # Upload fichier
    uploaded_file = st.file_uploader(
        "Choisissez un fichier CSV",
        type=['csv']
    )

    if uploaded_file is not None:
        try:
            # Lire le fichier
            df = pd.read_csv(uploaded_file)

            st.subheader("Aperçu des données")
            st.dataframe(df.head())

            # Vérifier les colonnes requises
            required_cols = ['Age', 'Salaire_Annuel', 'Epargne_Totale',
                           'Score_Credit_Externe', 'Niveau_Etude', 'Ville']

            missing_cols = [col for col in required_cols if col not in df.columns]

            if missing_cols:
                st.error(f"Colonnes manquantes : {missing_cols}")
                st.stop()

            # Paramètres
            duration = st.slider(
                "Durée du prêt (mois)",
                min_value=12,
                max_value=120,
                value=60,
                step=12,
                key="batch_duration"
            )

            # Bouton d'analyse
            if st.button("Analyser tous les clients", type="primary"):
                with st.spinner(f"Analyse de {len(df)} clients..."):
                    decisions = system.predict_batch(df, duration_months=duration)

                    # Créer DataFrame de résultats
                    results = pd.DataFrame(decisions)

                    # Ajouter les infos clients
                    results_full = pd.concat([
                        df[['Age', 'Salaire_Annuel', 'Niveau_Etude']].reset_index(drop=True),
                        results.reset_index(drop=True)
                    ], axis=1)

                    st.success(f"Analyse terminée pour {len(df)} clients")

                    # Statistiques
                    st.subheader("Statistiques Globales")
                    col1, col2, col3 = st.columns(3)

                    with col1:
                        acceptes = (results_full['Decision'] == 'Accepté').sum()
                        st.metric("Acceptés", acceptes,
                                 delta=f"{acceptes/len(df)*100:.1f}%")

                    with col2:
                        refuses = (results_full['Decision'] == 'Refusé').sum()
                        st.metric("Refusés", refuses,
                                 delta=f"{refuses/len(df)*100:.1f}%")

                    with col3:
                        ajustes = (results_full['Decision'] == 'Ajusté').sum()
                        st.metric("Ajustés", ajustes,
                                 delta=f"{ajustes/len(df)*100:.1f}%")

                    # Tableau complet
                    st.subheader("Résultats Détaillés")
                    st.dataframe(results_full, use_container_width=True)

                    # Téléchargement
                    csv = results_full.to_csv(index=False).encode('utf-8')
                    st.download_button(
                        label="Télécharger les résultats (CSV)",
                        data=csv,
                        file_name="resultats_credit.csv",
                        mime="text/csv"
                    )

        except Exception as e:
            st.error(f"Erreur lors de la lecture du fichier : {e}")
            st.exception(e)

# ==============================================================================
# PAGE 3 : À PROPOS
# ==============================================================================

def page_about():
    st.header("À Propos")

    st.markdown("""
    ## Système de Décision de Crédit Bancaire

    Cette application utilise un système de Machine Learning pour évaluer
    automatiquement les demandes de crédit bancaire.

    ### Architecture du Système

    1. **Preprocessing Pipeline**
       - Nettoyage des données
       - Feature engineering (ratio épargne/salaire)
       - Imputation intelligente
       - Encodage (ordinal + one-hot)
       - Scaling multi-stratégie

    2. **Modèle de Classification**
       - Régression Logistique calibrée
       - Prédiction du risque de défaut
       - Seuil optimisé pour 75% de recall

    3. **Modèle de Régression**
       - Ridge avec transformation log
       - Estimation du montant du prêt
       - Smearing factor pour correction du biais

    4. **Règles Métier**
       - Salaire minimum : 18,000€/an
       - Taux d'endettement maximum : 33%
       - Taux d'intérêt dynamique selon le risque

    ### Technologies Utilisées

    - **Python** : Langage principal
    - **Scikit-learn** : Pipeline ML
    - **Streamlit** : Interface web
    - **Pandas** : Manipulation de données

    ### Auteur

    Projet développé dans le cadre d'un pipeline complet de Data Science
    appliqué au crédit bancaire.

    ### Contact

    Pour toute question ou suggestion, n'hésitez pas à me contacter.
    """)

# ==============================================================================
# FONCTION D'AFFICHAGE DE LA DÉCISION
# ==============================================================================

def display_decision(decision):
    """Affiche la décision de manière visuelle."""

    # Couleur selon la décision
    if decision['Decision'] == 'Accepté':
        color = "green"
        icon = "✅"
    elif decision['Decision'] == 'Ajusté':
        color = "orange"
        icon = "⚠️"
    else:
        color = "red"
        icon = "❌"

    # Titre de la décision
    st.markdown(f"## {icon} Décision : **:{color}[{decision['Decision']}]**")

    # Affichage selon le type de décision
    if decision['Decision'] in ['Accepté', 'Ajusté']:
        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Montant Final",
                f"{decision.get('Montant_Final', 0):,.0f} €"
            )

        with col2:
            st.metric(
                "Mensualité",
                f"{decision.get('Mensualite', 0):,.2f} €"
            )

        with col3:
            st.metric(
                "Taux d'Intérêt",
                f"{decision.get('Taux_Propose', 0)*100:.1f}%"
            )

        # Détails supplémentaires
        with st.expander("Détails de l'Analyse"):
            st.write(f"**Montant proposé par le modèle** : {decision.get('Montant_Modele', 0):,.2f} €")
            st.write(f"**Capacité d'emprunt maximale** : {decision.get('Montant_Max_Autorise', 0):,.2f} €")
            st.write(f"**Niveau de risque** : {decision.get('Niveau_Risque', 0):.1%}")
            st.write(f"**Ratio d'endettement** : {decision.get('Ratio_Endettement', 0):.1%}")

            # Jauge de risque
            risque = decision.get('Niveau_Risque', 0)
            st.progress(risque, text=f"Risque de défaut : {risque:.1%}")

            # Justification
            st.info(f" {decision.get('Justification', 'N/A')}")

    else:
        # Cas refusé
        st.error(f"**Motif** : {decision.get('Raison', decision.get('Motif', 'Non spécifié'))}")

        if 'Niveau_Risque' in decision and decision['Niveau_Risque'] is not None:
            st.write(f"**Niveau de risque** : {decision['Niveau_Risque']:.1%}")

        if 'Probabilité_Défaut' in decision:
            st.write(f"**Probabilité de défaut** : {decision['Probabilité_Défaut']:.1%}")

# ==============================================================================
# POINT D'ENTRÉE
# ==============================================================================

if __name__ == "__main__":
    main()